import type {Metadata} from "next";

import {Roboto, Open_Sans} from "next/font/google";

import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/ui/Footer";

const roboto = Roboto({
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const openSans = Open_Sans({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bargiu Electro",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className={`bg-[#FFEEEE] text-black ${roboto.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
